### ISSUE TITLE
グラフ

### ISSUE THREAD

**Issue by xiawatanabe** [kikirinrin/sa_templates#8]
グラフの配置は評価報告書により様々。ある程度制約・・・1ページあたり3枚、6枚、8枚とか・・・をつける？Excelのグラフは。

**Comment by kikirinrin** [comment]
図の配置も，テンプレートで対応できるようにしています．

6枚貼るつもりなら
```
\TwoOfSixFigs{
  {FNAME_FIG1}{CAPTION_FIG1}{LABEL_FIG1}
  {FNAME_FIG2}{CAPTION_FIG2}{LABEL_FIG2}
}
```
を3回繰り返し，

8枚貼るつもりなら
```
\TwoOfEightFigs{
  {FNAME_FIG1}{CAPTION_FIG1}{LABEL_FIG1}
  {FNAME_FIG2}{CAPTION_FIG2}{LABEL_FIG2}
}
```
を4回繰り返す的な感じです．

**Comment by kikirinrin** [comment]
TeXのマクロを裸でした場合，引数の制限からこんな残念な感じになっていますが，
perl 正規表現と併用すれば，本文中に  `\eightfigs{...}` と書いておいて，
これを上記の4回繰り返しマクロに展開することもできそうです．
