### ISSUE TITLE
ファイル名

### ISSUE THREAD

**Issue by xiawatanabe** [kikirinrin/sa_templates#9]
系群・学名つきのファイル名は見分けるのに時間がかかる。各ユーザーはyouyaku.texなどのファイル名をつかって評価報告書を作成し、全体を編集する段階で系群・学名を付け足す？（Windowsの場合はpowershellで一瞬）

**Comment by kikirinrin** [comment]
系群ごとにリポジトリを作る方法に変更することで，系群名をファイル名に入れなくてもよいようにします．
